<a href="https://colab.research.google.com/github/Sosswood/Machine-Learning/blob/main/Unit07_Ex2_perceptron_AND_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Author: Dr Mike Lakoju, CardiffMet

### Import Library

In [1]:
import numpy as np

### Define "Inputs, outputs and weights" as Numpy arrays

#### Inputs

In [38]:
# Creating input values as a matrix not as a vector
inputs = np.array([[0,2], [1,2], [1,0], [1,2],[2,2]])

In [39]:
# Chcking the shape of the inputs

inputs.shape

(5, 2)

#### Outputs

In [40]:
outputs = np.array([0, 0, 0, 1])

In [41]:
#Checking the shape of the outputs

outputs.shape

(4,)

#### Weights

In [42]:
# one weight for x1 and one for x2
weights = np.array([0.0, 0.0])

#### Learning Rate

In [43]:
learning_rate = 0.1

## Step function

In [44]:
# This is our Activation function

def step_function(sum):
  if (sum >= 1):
    #print(f'The Sum of Weights is Greater or equal to 1')
    return 1
  else:
        #print(f'The Sum of Weights is NOT > or = to 1')
        return 0

## Process Output

<b>We define a function that allows us to calculate/ process the output. The function accepts an instance of our data, then calculate the sum function using Numpy. Finally, we check the output by passing it through the "Step Function."</b>

In [45]:
def cal_output(instance):
  sum_func = instance.dot(weights)
  return step_function(sum_func)

We pass it as alist in a numpy array ...

In [46]:
cal_output(np.array([[2,1]]))

0

## Train

In [47]:
# Check the number of outputs

len(outputs)

4

In [48]:
# Checking the index of the input at postion 3 ..
# this is the last inpute value
inputs[3]

array([1, 2])

In [49]:
inputs

array([[0, 2],
       [1, 2],
       [1, 0],
       [1, 2],
       [2, 2]])

<b>Note that:</b> usually, we will need to define the number of epochs, because we will never really get a value of zero when dealing with real-world data. However, for this small data, we will run the loop till we obtain zero error

In [50]:
def train():
    #
    total_error_value = 1
    # While the total_error_value is not equal to zero. we are asumming that at the start of running our network there will be no zero
    while (total_error_value != 0):
        #making the total_error 0 so we can do other calculations
        total_error_value = 0
        #Looping into each row of the dataset (remember indexing in python starts at zero hence 0-3 which are 4 values)
        for i in range(len(outputs)):
            #Calculating predictions
            prediction = cal_output(inputs[i])
            # Calculating the absolute value of the error
            error = abs(outputs[i] - prediction)
            #Updating the error
            total_error_value  += error

            if error > 0:
                for j in range(len(weights)):
                    #updating the weights for x1 and x2
                    weights[j] = weights[j] + (learning_rate * inputs[i][j] * error)
                    print('Weight updated to: ' + str(weights[j]))
        print('Total error Value: ' + str(total_error_value))

In [51]:
train()

Streaming output truncated to the last 5000 lines.
Weight updated to: 323325.49999652593
Weight updated to: 646652.5999930515
Weight updated to: 323325.5999965259
Weight updated to: 646652.5999930515
Total error Value: 3
Weight updated to: 323325.5999965259
Weight updated to: 646652.7999930514
Weight updated to: 323325.6999965259
Weight updated to: 646652.9999930514
Weight updated to: 323325.79999652586
Weight updated to: 646652.9999930514
Total error Value: 3
Weight updated to: 323325.79999652586
Weight updated to: 646653.1999930514
Weight updated to: 323325.89999652584
Weight updated to: 646653.3999930513
Weight updated to: 323325.9999965258
Weight updated to: 646653.3999930513
Total error Value: 3
Weight updated to: 323325.9999965258
Weight updated to: 646653.5999930513
Weight updated to: 323326.0999965258
Weight updated to: 646653.7999930512
Weight updated to: 323326.1999965258
Weight updated to: 646653.7999930512
Total error Value: 3
Weight updated to: 323326.1999965258
Weight upd

KeyboardInterrupt: 

## Classification

In [52]:
# Now we have the final weights that will be used to classify new instances of the data after training.

weights

array([323468.29999649, 646938.19999298])

In [53]:
cal_output(np.array([0,0]))

0

In [54]:
cal_output(np.array([0,1]))

1

In [55]:
cal_output(np.array([1,0]))

1

In [56]:
cal_output(np.array([1,1]))

1

In [57]:
cal_output(np.array([2,2]))

1

In [59]:
cal_output(np.array([1,2]))

1